name: Action - Create a tag

inputs:
  ref_name:
    description: "The branch to tag"
    required: true
    type: string

  tag:
    description: "The tag to create"
    required: true
    type: string

  github_token:
    description: "The github token"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref_name }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - name: Create tag
      run: |
        echo "Creating tag ${{ inputs.tag }}"
        git tag ${{ inputs.tag }}
        git push origin ${{ inputs.tag }}
