name: Action - Create a tag

inputs:
  ref_name:
    description: "The branch to tag"
    required: true
    type: string

  tag_name:
    description: "The tag to create"
    required: true
    type: string

  github_token:
    description: "The github token"
    required: true
    type: string

outputs:
  tag_exists:
    description: "Whether the tag already exists"
    value: ${{ steps.create-tag.outputs.tag_exists }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref_name }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - name: Create tag
      id: create-tag
      shell: bash
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "No github token provided"
          exit 1
        fi
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "No tag name provided"
          exit 1
        fi
        echo "Creating tag ${{ inputs.tag_name }}"
        if git rev-parse -q --verify "refs/tags/${{ inputs.tag_name }}"; then
          echo "Tag ${{ inputs.tag_name }} already exists"
          echo "tag_exists=true" >> $GITHUB_OUTPUT
          exit 1
        else 
          echo "tag_exists=false" >> $GITHUB_OUTPUT
        fi
        git tag ${{ inputs.tag_name }}
        git push origin --tags