name: Action - Get new version

inputs:
    release-branch:
        description: "The branch to compare against"
        required: true
        default: "main"
        type: string
    
    prefix:
        description: "The prefix to use for the version"
        required: false
        default: "v"
        type: string
    
    log-paths:
        description: "The path to the sub module"
        required: false
        default: "./"
        type: string

outputs:
    version:
        description: "The new version"
        value: ${{ steps.git-version.outputs.version }}
    previous-version:
        description: "The previous version"
        value: ${{ steps.git-version.outputs.previous-version }}

runs:
    using: "composite"
  
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
  
      - name: Git Version
        id: git-version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: ${{ inputs.release-branch }}
          prefix: ${{ inputs.prefix }}
          log-paths: ${{ inputs.log-paths }}    