name: Build on Pre-Release

on:
  workflow_call:
    inputs:
      release-tag:
        description: "The tag for this release"
        required: true
        type: string
      release-body:
        description: "The body for this release"
        required: true
        type: string
      release-id:
        description: "The id for this release"
        required: true
        type: string
      is-pr:
        description: "Whether this is a PR release"
        required: false
        default: false
        type: boolean

  # release:
    # types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.release-tag }}
        fetch-depth: 0

    - name: Debug
      run: |
        echo "Release: ${{ toJson(github.event) }}"

    - name: Run build script
      run: |
        echo "Running ./ops/scripts/build.sh"


    - name: Update release body
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const releaseId = ${{ inputs.release-id }};
          const existingBody = '${{ inputs.release-body }}';
          const updatedBody = `${existingBody}\n\nReleased`;
          
          await github.rest.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId,
            body: updatedBody,
          });
