on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/*
            - release/*

jobs:
    get-version:
        uses: ./.github/workflows/version.yml
        with:
            release-branch: "main"
            prefix: "v"

    build:
        needs:
            - get-version
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Hello world
              run: echo "Hello world"
            - name: "Show versions:"
              run: | 
                echo "New Version: ${{ needs.get-version.outputs.version }}"
                echo "Previous Version: ${{ needs.get-version.outputs.previous-version }}"