name: Check Pull Request

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref_name:
        description: "The branch name to check for pull request"
        required: true
        type: string
    outputs:
      has_pull_request:
        description: "Whether a pull request exists for the branch"
        value: ${{ jobs.check_pull_request.outputs.has_pull_request }}
      pull_request_number:
        description: "The number of the pull request"
        value: ${{ jobs.check_pull_request.outputs.pull_request_number }}

jobs:
  check_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Check for pull request
      id: check_pr
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const branch = '${{ inputs.ref_name || github.ref_name || github.head_ref }}';
          const pulls = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            head: `${context.repo.owner}:${branch}`,
          });

          if (pulls.data.length > 0) {
            core.setOutput('has_pull_request', 'true');
            core.setOutput('pull_request_number', pulls.data[0].number);

            console.log(`Pull request #${pulls.data[0].number} found for branch ${branch}`);
          } else {
            core.setOutput('has_pull_request', 'false');
            console.log(`No pull request found for branch ${branch}`);
          }

    - name: Print pull request status
      run: |
        echo "Has Pull Request: ${{ steps.check_pr.outputs.has_pull_request }}"
        echo "Pull Request Number: ${{ steps.check_pr.outputs.pull_request_number }}"