name: Manual Pre-Release

on:
  workflow_dispatch:

permissions: write-all
#   contents: write

jobs:
    get-version:
        uses: ./.github/workflows/version.yml
        with:
            release-branch: "main"
            prefix: "v"
    
    create-pre-release:
        runs-on: ubuntu-latest
        needs:
            - get-version
        outputs:
            release-id: ${{ steps.create-pre-release.outputs.id }}
        steps:
            - uses: actions/checkout@v4

            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                custom_tag: dev-${{ needs.get-version.outputs.version }}

            - name: Create Pre-Release
              id: create-pre-release
              uses: ncipollo/release-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag: dev-${{ needs.get-version.outputs.version }} 
                name: "[DEV-${{ github.ref_name || github.head_ref }}] ${{ needs.get-version.outputs.version }}"
                prerelease: true
                body: |
                  Pre-release from branch ${{ github.ref_name || github.head_ref }}

    execute-pre-release:
      needs:
        - create-pre-release
        - get-version
      uses: ./.github/workflows/build-on-pre-release.yml
      with:
          release-tag: dev-${{ needs.get-version.outputs.version }}
          release-body: "Pre-release from branch ${{ github.ref_name || github.head_ref }}"
          release-id: ${{ needs.create-pre-release.outputs.release-id }}