name: Create Release

on:
    workflow_dispatch:
        inputs:
            is_draft_release:
                description: "Whether this is a draft-release"
                required: false
                default: false
                type: boolean
            
            project:
                description: "The project for this release"
                required: true
                type: choice
                options:
                    - project1
                    - project2

jobs:
    release:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}
                fetch-depth: 0

            - name: Git Version
              id: git-version
              uses: codacy/git-version@2.8.0
              with:
                release-branch: 'main'
                prefix: 'v'
                log-paths: './'
        
            - name: Debug
              id: create-tag-name
              run: |
                    echo "Project: ${{ inputs.project }}"
                    echo "Version: ${{ steps.git-version.outputs.version }}"
                    echo "tag=${{ steps.git-version.outputs.version }}-${{ inputs.project }}" >> $GITHUB_OUTPUT

                    
            - name: Create and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                custom_tag: ${{ steps.create-tag-name.outputs.tag }}

            # - name: Create tag
            #   id: create-tag
            #   uses: ./.github/workflows/tag
            #   with:
            #     github_token: ${{ secrets.GITHUB_TOKEN }}
            #     ref_name: ${{ steps.check-release-comment.outputs.branch }}
            #     tag_name: ${{ steps.create-tag-name.outputs.new_version }}
    
            
            - name: Genearte body
              id: generate-body
              run: |
                echo "Generating body"
                body="Project ${{ inputs.project }} release ${{ steps.git-version.outputs.version }}"
                echo "body=$body" >> $GITHUB_OUTPUT

            - name: Create Release
              id: create-release
              uses: ncipollo/release-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag: ${{ steps.git-version.outputs.version }}
                name: "[${{ inputs.project }}] ${{ steps.git-version.outputs.version }}"
                prerelease: ${{ inputs.is_draft_release }}
                body: ${{ steps.generate-body.outputs.body }}

            - name: Build
              uses: ./.github/workflows/build
              with:
                ref_name: ${{ steps.create-tag-name.outputs.tag }}
                project: ${{ inputs.project }}
                tag: ${{ steps.create-tag-name.outputs.tag }}
    


            - name: Update release body
              uses: actions/github-script@v7
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const releaseId = ${{ steps.create-release.outputs.id }};
                    const existingBody = '${{ steps.generate-body.outputs.body }}';
                    const updatedBody = `${existingBody}\n\nReleased`;
                    
                    await github.rest.repos.updateRelease({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        release_id: releaseId,
                        body: updatedBody,
                    });

                    const reactionContent = 'rocket'; 
                    await github.rest.reactions.createForRelease({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      release_id: releaseId,
                      content: reactionContent,
                    });                                              
          
                    
                    
