name: Manual Pre-Release

on:
  workflow_dispatch:

permissions: write-all
#   contents: write

jobs:
    get-version:
        uses: ./.github/workflows/version.yml
        with:
            release-branch: "main"
            prefix: "v"

    check-for-pr:
        uses: ./.github/workflows/check-for-pull-request.yml
        with:
            ref_name: ${{ github.ref_name || github.head_ref }}
    
    create-pre-release:
        runs-on: ubuntu-latest
        needs:
            - get-version
            - check-for-pr
        outputs:
            release-id: ${{ steps.create-pre-release.outputs.id }}
            release-tag: ${{ steps.generate-tag-and-body.outputs.tag }}
            release-body: ${{ steps.generate-tag-and-body.outputs.body }}                

        steps:
            - uses: actions/checkout@v4

            - name: Generate tag and body
              id: generate-tag-and-body
              run: |
                echo "Generating tag and body"
                if [ "${{ needs.check-for-pr.outputs.has_pull_request }}" == "true" ]; then
                    echo "tag=pr-${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
                    echo "body=Pre-release from PR ${{ github.ref_name || github.head_ref }}" >> $GITHUB_OUTPUT
                else
                    echo "tag=dev-${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
                    echo "body=Pre-release from branch ${{ github.ref_name || github.head_ref }}" >> $GITHUB_OUTPUT
                fi
                echo "tag=dev-${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
                echo "body=Pre-release from branch ${{ github.ref_name || github.head_ref }}" >> $GITHUB_OUTPUT

            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                custom_tag: ${{ steps.generate-tag-and-body.outputs.tag }}

            - name: Create Pre-Release
              id: create-pre-release
              uses: ncipollo/release-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag: ${{ steps.generate-tag-and-body.outputs.tag }}
                name: "[DEV-${{ github.ref_name || github.head_ref }}] ${{ needs.get-version.outputs.version }}"
                prerelease: true
                body: ${{ steps.generate-tag-and-body.outputs.body }}
                  
    execute-pre-release:
      needs:
        - create-pre-release
        - get-version
      uses: ./.github/workflows/build-on-pre-release.yml
      # We need to call the above workflow through a workflow_call as a 'on: release' event is not executed if the release
      # is created from a workflow unless a Personal GITHUB token is used.
      with:
          release-tag: ${{ needs.create-pre-release.outputs.release-tag }}
          release-body: ${{ needs.create-pre-release.outputs.release-body }}
          release-id: ${{ needs.create-pre-release.outputs.release-id }}
          is-pr: ${{ needs.check-for-pr.outputs.has_pull_request }}