name: Manual Pre-Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create the pre-release from'
        required: true
        default: 'main'

jobs:
    get-version:
        uses: ./.github/workflows/version.yml
        with:
            release-branch: "main"
            prefix: "v"
    
    create-pre-release:
        runs-on: ubuntu-latest
        needs:
            - get-version
        steps:
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.inputs.branch }}

            - name: Create Pre-Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ needs.get-version.outputs.version }}
                release_name: Pre-Release ${{ needs.get-version.outputs.version }}
                body: |
                  Pre-release from branch ${{ github.event.inputs.branch }}
                  draft: false
                  prerelease: true