name: Manual Pre-Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    get-version:
        uses: ./.github/workflows/version.yml
        with:
            release-branch: "main"
            prefix: "v"
    
    create-pre-release:
        runs-on: ubuntu-latest
        needs:
            - get-version
        steps:
            - uses: actions/checkout@v4

            - name: Create Pre-Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ needs.get-version.outputs.version }}
                release_name: "[DEV-${{ github.ref_name || github.head_ref }}] ${{ needs.get-version.outputs.version }}"
                body: |
                  Pre-release from branch ${{ github.ref_name || github.head_ref }}