name: Create Release

on:
    workflow_dispatch:
        inputs:
            is_draft_release:
                description: "Whether this is a draft-release"
                required: false
                default: true
                type: boolean
            
            project:
                description: "The project for this release"
                required: true
                type: choice
                options:
                    - project1
                    - project2

permissions: write-all

jobs:
    release:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}
                fetch-depth: 0

            - name: Git Version
              id: git-version
              uses: codacy/git-version@2.8.0
              with:
                release-branch: 'main'
                prefix: 'v'
                log-paths: './'
        
            - name: Debug
              id: create-tag-and-version-name
              run: |
                    echo "Project: ${{ inputs.project }}"
                    version="${{ steps.git-version.outputs.version }}"
                    echo "Version: ${version}"
                    tag="${version}-${{ inputs.project }}"

                    echo "Tag: $tag"
                    echo "tag=$tag" >> $GITHUB_OUTPUT
                    echo "version=${version}" >> $GITHUB_OUTPUT

                    
            - name: Create and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                custom_tag: ${{ steps.create-tag-and-version-name.outputs.tag }}
                tag_prefix: ''

            - name: Genearte body
              id: generate-body
              run: |
                echo "Generating body"
                body="Project: ${{ inputs.project }} \nRelease: ${{ steps.create-tag-and-version-name.outputs.version }}"
                echo -e "body=$body" >> $GITHUB_OUTPUT

            - name: Build
              uses: ./.github/workflows/build
              with:
                ref_name: ${{ steps.create-tag-and-version-name.outputs.tag }}
                tag: ${{ steps.create-tag-and-version-name.outputs.tag }}
                project: ${{ inputs.project }}
                
    
            - name: Create Release
              id: create-release
              uses: ncipollo/release-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag: ${{ steps.create-tag-and-version-name.outputs.version }}
                name: "[${{ inputs.project }}] ${{ steps.create-tag-and-version-name.outputs.version }}"
                prerelease: ${{ inputs.is_draft_release }}
                body: ${{ steps.generate-body.outputs.body }}                
                artifacts: "./artifact.txt"


            - name: Add reaction
              uses: actions/github-script@v7
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const releaseId = ${{ steps.create-release.outputs.id }};

                    const reactionContent = 'rocket'; 
                    await github.rest.reactions.createForRelease({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      release_id: releaseId,
                      content: reactionContent,
                    });                                              
          
                    
                    
