on: 
    issue_comment:
        types: 
            - created

permissions: write-all
    # contents: read
    # issues: write


jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - id: check-release-comment
        name: Check for release comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = '${{ github.event.comment.body }}';
            core.setOutput('create_release', comment === 'release');

      - name: Add reaction to release
        uses: actions/github-script@v6
        if: steps.check-release-comment.outputs.create_release == 'true'
        env:
          COMMENT_ID: ${{ github.event.comment.id }}
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const commentId = ${{ env.COMMENT_ID }};
              const reactionContent = 'rocket'; // You can change this to any valid reaction type
            
              await github.rest.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: commentId,
                content: reactionContent,
              });          