on: 
    issue_comment:
        types: 
            - created

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          echo A comment on PR $NUMBER: $COMMENT
          if [ "$COMMENT" == "release" ]; then
            echo "create_release=true" >> $GITHUB_OUTPUT
          else
            echo "create_release=false" >> $GITHUB_OUTPUT
          fi
          echo '${{ toJson(github.event) }}'
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ github.event.comment.body }}

      - name: Add reaction to release
        uses: actions/github-script@v6
        if: steps.pr_commented.outputs.create_release == 'true'
        env:
          COMMENT_ID: ${{ github.event.comment.id }}
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const commentId = ${{ env.COMMENT_ID }};
              const reactionContent = 'rocket'; // You can change this to any valid reaction type
            
              await github.rest.reactions.createForComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: commentId,
                content: reactionContent,
              });          