name: On Release Workflow

on:
  release:
    # types: [published, unpublished, created, edited, deleted, prereleased, released]    
    types: [released]    

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ !github.event.release.draft }}

        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.event.release.tag }}
                fetch-depth: 0

            - name: Run build script
              run: |
                echo "Running ./ops/scripts/build.sh --project ${{ github.event.release.tag_name }}"
                echo "${{ toJson(github.event) }}"

