name: On Release Workflow

on:
  release:
    types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.event.release.tag }}
                fetch-depth: 0

            - name: Run build script
              run: |
                echo "Running ./ops/scripts/build.sh --project ${{ github.event.release.tag_name }}"
                
            # - name: Build
            #   uses: ./.github/workflows/build
            #   if: steps.check-release-comment.outputs.do_release == 'true'
            #   with:
            #     ref_name: ${{ steps.create-tag-name.outputs.new_version }}
            #     project: ${{ steps.check-release-comment.outputs.project }}
            #     tag: ${{ steps.create-tag-name.outputs.new_version }}
        