name: Worflow Call - Create Release

on:
  workflow_call:
    inputs:
      version:
        description: "The version to release"
        required: true
        type: string
      release-name:
        description: "The name for this release"
        required: true
        type: string
      release-body:
        description: "The body for this release"
        required: true
        type: string
    #   release-id:
    #     description: "The id for this release"
    #     required: true
    #     type: string
      is-pre-release:
        description: "Whether this is a pre release"
        required: false
        default: false
        type: boolean
      project:
        description: "The project for this release"
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
        - name: create-tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ inputs.version }}

        - name: Create Release
          id: create-release
          uses: ncipollo/release-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            prerelease: ${{ inputs.is-pre-release }}
            tag: ${{ inputs.version }}
            name: ${{ inputs.release-name }}            
            body: ${{ inputs.release-body }}